/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnalyticsReportingSummaryResponse } from '../model/models';
import { AnalyticsSummaryResponse } from '../model/models';
import { AppSchemasOperationsErrorResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetAnalyticsSummaryRequestParams {
    startDate?: string | null;
    endDate?: string | null;
}

export interface GetReportingSummaryRequestParams {
    startDate?: string | null;
    endDate?: string | null;
}


export interface AnalyticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Analytics Summary
     * Return the Analytics page summary from the loaded analytics schema.
     * @endpoint get /analytics/summary
* @param requestParameters
     */
    getAnalyticsSummary(requestParameters: GetAnalyticsSummaryRequestParams, extraHttpRequestParams?: any): Observable<AnalyticsSummaryResponse>;

    /**
     * Get Reporting Summary
     * Return the Reporting dashboard tiles and drilldowns from real stored data.
     * @endpoint get /analytics/reporting-summary
* @param requestParameters
     */
    getReportingSummary(requestParameters: GetReportingSummaryRequestParams, extraHttpRequestParams?: any): Observable<AnalyticsReportingSummaryResponse>;

}
