export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './image.service';
import { ImageService } from './image.service';
export * from './image.serviceInterface';
export * from './inspection.service';
import { InspectionService } from './inspection.service';
export * from './inspection.serviceInterface';
export * from './shifts.service';
import { ShiftsService } from './shifts.service';
export * from './shifts.serviceInterface';
export * from './smartfleet.service';
import { SmartfleetService } from './smartfleet.service';
export * from './smartfleet.serviceInterface';
export * from './vehicle.service';
import { VehicleService } from './vehicle.service';
export * from './vehicle.serviceInterface';
export const APIS = [AuthService, ImageService, InspectionService, ShiftsService, SmartfleetService, VehicleService];
