/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FirebaseRefreshRequest } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { UserCreateRequest } from '../model/models';
import { UserCreateResponse } from '../model/models';
import { UserLoginRequest } from '../model/models';
import { UserLoginResponse } from '../model/models';
import { UserRefreshResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateUserAuthUsersPostRequestParams {
    userCreateRequest: UserCreateRequest;
}

export interface GetTokenAuthGetTokenPostRequestParams {
    userLoginRequest: UserLoginRequest;
}

export interface RefreshTokenAuthRefreshPostRequestParams {
    firebaseRefreshRequest: FirebaseRefreshRequest;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new application user
     * Create a Firebase user, set their role claim, then insert the DB record.
     * @endpoint post /auth/users
* @param requestParameters
     */
    createUserAuthUsersPost(requestParameters: CreateUserAuthUsersPostRequestParams, extraHttpRequestParams?: any): Observable<UserCreateResponse>;

    /**
     * Get app login token and user context
     * Sign in through Firebase and return the app\&#39;s enriched login payload.  Firebase issues the tokens, but the application also needs local user data such as role, split name fields, and the Firebase UID stored in the app\&#39;s own database.
     * @endpoint post /auth/get_token
* @param requestParameters
     */
    getTokenAuthGetTokenPost(requestParameters: GetTokenAuthGetTokenPostRequestParams, extraHttpRequestParams?: any): Observable<UserLoginResponse>;

    /**
     * Refresh an expired access token
     * Exchange a &#x60;&#x60;refresh_token&#x60;&#x60; for a new &#x60;&#x60;id_token&#x60;&#x60; and app user context.  Call this when the bearer token has expired. The returned &#x60;&#x60;access_token&#x60;&#x60; replaces the old token for subsequent requests and includes the same user context as &#x60;&#x60;/auth/get_token&#x60;&#x60;.
     * @endpoint post /auth/refresh
* @param requestParameters
     */
    refreshTokenAuthRefreshPost(requestParameters: RefreshTokenAuthRefreshPostRequestParams, extraHttpRequestParams?: any): Observable<UserRefreshResponse>;

}
