/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppSchemasOperationsErrorResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { PhotoResponse } from '../model/models';
import { SelfieResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetAllPhotosImagePhotosGetRequestParams {
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}

export interface GetAllSelfiesImageSelfiesGetRequestParams {
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}

export interface GetPhotosByInspectionImagePhotosByInspectionIdsGetRequestParams {
    inspectionIds: Array<number>;
}

export interface GetSelfiesByShiftImageSelfiesByShiftIdsGetRequestParams {
    shiftIds: Array<number>;
}

export interface ViewPhotoImagePhotosPhotoIdViewGetRequestParams {
    photoId: number;
}

export interface ViewSelfieImageSelfiesSelfieIdViewGetRequestParams {
    selfieId: number;
}


export interface ImageServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get all inspection photos with optional date range and limit
     * Return inspection photo rows, optionally filtered by timestamp range.
     * @endpoint get /image/photos
* @param requestParameters
     */
    getAllPhotosImagePhotosGet(requestParameters: GetAllPhotosImagePhotosGetRequestParams, extraHttpRequestParams?: any): Observable<Array<PhotoResponse>>;

    /**
     * Get all selfies with optional date range and limit
     * Return selfie rows, optionally filtered by timestamp range.
     * @endpoint get /image/selfies
* @param requestParameters
     */
    getAllSelfiesImageSelfiesGet(requestParameters: GetAllSelfiesImageSelfiesGetRequestParams, extraHttpRequestParams?: any): Observable<Array<SelfieResponse>>;

    /**
     * Get inspection photos by inspection IDs
     * Return all shift-inspection photos attached to the specified inspection IDs.
     * @endpoint get /image/photos/by_inspection_ids
* @param requestParameters
     */
    getPhotosByInspectionImagePhotosByInspectionIdsGet(requestParameters: GetPhotosByInspectionImagePhotosByInspectionIdsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<PhotoResponse>>;

    /**
     * Get selfies by shift IDs
     * Return all selfies that belong to the specified shift IDs.
     * @endpoint get /image/selfies/by_shift_ids
* @param requestParameters
     */
    getSelfiesByShiftImageSelfiesByShiftIdsGet(requestParameters: GetSelfiesByShiftImageSelfiesByShiftIdsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<SelfieResponse>>;

    /**
     * View a single inspection photo as an image
     * Decode and serve the base64 image stored for one inspection photo.
     * @endpoint get /image/photos/{photo_id}/view
* @param requestParameters
     */
    viewPhotoImagePhotosPhotoIdViewGet(requestParameters: ViewPhotoImagePhotosPhotoIdViewGetRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * View a single shift selfie as an image
     * Decode and serve the base64 image stored for one shift selfie.
     * @endpoint get /image/selfies/{selfie_id}/view
* @param requestParameters
     */
    viewSelfieImageSelfiesSelfieIdViewGet(requestParameters: ViewSelfieImageSelfiesSelfieIdViewGetRequestParams, extraHttpRequestParams?: any): Observable<any>;

}
