/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppSchemasOperationsErrorResponse } from '../model/models';
import { GroupedBusInspectionResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetAllBusInspectionsInspectionBusInspectionsGetRequestParams {
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}

export interface GetBusInspectionsByBusInspectionBusInspectionsByBusIdsGetRequestParams {
    busIds: Array<string>;
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}

export interface GetBusInspectionsByShiftInspectionBusInspectionsByShiftIdsGetRequestParams {
    shiftIds: Array<number>;
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}

export interface GetBusInspectionsByUserInspectionBusInspectionsByUserIdsGetRequestParams {
    userIds: Array<string>;
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}


export interface InspectionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get all bus inspections with optional date range and limit
     * Return grouped bus inspections across all shifts that match the filters.
     * @endpoint get /inspection/bus_inspections
* @param requestParameters
     */
    getAllBusInspectionsInspectionBusInspectionsGet(requestParameters: GetAllBusInspectionsInspectionBusInspectionsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<GroupedBusInspectionResponse>>;

    /**
     * Get bus inspections by bus IDs/VINs with optional date range and limit
     * Return grouped bus inspections for a selected set of VINs / bus IDs.
     * @endpoint get /inspection/bus_inspections/by_bus_ids
* @param requestParameters
     */
    getBusInspectionsByBusInspectionBusInspectionsByBusIdsGet(requestParameters: GetBusInspectionsByBusInspectionBusInspectionsByBusIdsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<GroupedBusInspectionResponse>>;

    /**
     * Get bus inspections by shift IDs with optional date range and limit
     * Return grouped bus inspections for a selected set of shift IDs.
     * @endpoint get /inspection/bus_inspections/by_shift_ids
* @param requestParameters
     */
    getBusInspectionsByShiftInspectionBusInspectionsByShiftIdsGet(requestParameters: GetBusInspectionsByShiftInspectionBusInspectionsByShiftIdsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<GroupedBusInspectionResponse>>;

    /**
     * Get bus inspections by user IDs with optional date range and limit
     * Return grouped bus inspections recorded by selected monitor user IDs.
     * @endpoint get /inspection/bus_inspections/by_user_ids
* @param requestParameters
     */
    getBusInspectionsByUserInspectionBusInspectionsByUserIdsGet(requestParameters: GetBusInspectionsByUserInspectionBusInspectionsByUserIdsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<GroupedBusInspectionResponse>>;

}
