/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { AppSchemasOperationsErrorResponse } from '../model/appSchemasOperationsErrorResponse';
// @ts-ignore
import { HTTPValidationError } from '../model/hTTPValidationError';
// @ts-ignore
import { MonitorSummaryResponse } from '../model/monitorSummaryResponse';
// @ts-ignore
import { ShiftCreate } from '../model/shiftCreate';
// @ts-ignore
import { ShiftCreatedResponse } from '../model/shiftCreatedResponse';
// @ts-ignore
import { ShiftPageResponse } from '../model/shiftPageResponse';
// @ts-ignore
import { ShiftResponse } from '../model/shiftResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    ShiftsServiceInterface,
    CreateShiftShiftCreateShiftPostRequestParams,
    GetAllShiftsShiftShiftsGetRequestParams,
    GetShiftsPagedShiftShiftsPagedGetRequestParams,
    GetShiftsByIdsShiftShiftsByIdsGetRequestParams
} from './shifts.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class ShiftsService extends BaseService implements ShiftsServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Create Shift
     * Create a shift, then attach its selfies and nested bus inspections.  The shift row is written first because child rows need the database-assigned &#x60;&#x60;shift_id&#x60;&#x60;. After that, selfies and inspections are persisted using the nested request payload supplied by the client.
     * @endpoint post /shift/create_shift/
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public createShiftShiftCreateShiftPost(requestParameters: CreateShiftShiftCreateShiftPostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ShiftCreatedResponse>;
    public createShiftShiftCreateShiftPost(requestParameters: CreateShiftShiftCreateShiftPostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ShiftCreatedResponse>>;
    public createShiftShiftCreateShiftPost(requestParameters: CreateShiftShiftCreateShiftPostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ShiftCreatedResponse>>;
    public createShiftShiftCreateShiftPost(requestParameters: CreateShiftShiftCreateShiftPostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const shiftCreate = requestParameters?.shiftCreate;
        if (shiftCreate === null || shiftCreate === undefined) {
            throw new Error('Required parameter shiftCreate was null or undefined when calling createShiftShiftCreateShiftPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (HTTPBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('HTTPBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/shift/create_shift/`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ShiftCreatedResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: shiftCreate,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all shifts with optional date range and limit
     * Return shift rows with optional date-range filtering and pagination size.  Despite the name &#x60;&#x60;limit&#x60;&#x60;, this endpoint still returns a plain list of shift records. The filters are applied directly at the database query level to avoid loading unnecessary rows into memory.
     * @endpoint get /shift/shifts
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getAllShiftsShiftShiftsGet(requestParameters?: GetAllShiftsShiftShiftsGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<ShiftResponse>>;
    public getAllShiftsShiftShiftsGet(requestParameters?: GetAllShiftsShiftShiftsGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ShiftResponse>>>;
    public getAllShiftsShiftShiftsGet(requestParameters?: GetAllShiftsShiftShiftsGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ShiftResponse>>>;
    public getAllShiftsShiftShiftsGet(requestParameters?: GetAllShiftsShiftShiftsGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const startDate = requestParameters?.startDate;
        const endDate = requestParameters?.endDate;
        const startTime = requestParameters?.startTime;
        const endTime = requestParameters?.endTime;
        const limit = requestParameters?.limit;
        const userId = requestParameters?.userId;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'start_date',
            <any>startDate,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'end_date',
            <any>endDate,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'start_time',
            <any>startTime,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'end_time',
            <any>endTime,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'limit',
            <any>limit,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'user_id',
            <any>userId,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (HTTPBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('HTTPBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/shift/shifts`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ShiftResponse>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get monitor options with aggregate shift and inspection counts
     * Return lightweight monitor rows for dropdowns before loading details.  The Monitors page should not need to load every shift, inspection, and selfie before the selector is usable. This endpoint returns one row per monitor-like app user, plus any unknown user ID that already has shift rows.
     * @endpoint get /shift/monitors/summary
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getMonitorSummariesShiftMonitorsSummaryGet(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<MonitorSummaryResponse>>;
    public getMonitorSummariesShiftMonitorsSummaryGet(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<MonitorSummaryResponse>>>;
    public getMonitorSummariesShiftMonitorsSummaryGet(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<MonitorSummaryResponse>>>;
    public getMonitorSummariesShiftMonitorsSummaryGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        // authentication (HTTPBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('HTTPBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/shift/monitors/summary`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<MonitorSummaryResponse>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get shifts using server-side pagination, search, and sorting
     * Return one server-side page of shift rows for the PrimeNG lazy table.
     * @endpoint get /shift/shifts/paged
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getShiftsPagedShiftShiftsPagedGet(requestParameters?: GetShiftsPagedShiftShiftsPagedGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ShiftPageResponse>;
    public getShiftsPagedShiftShiftsPagedGet(requestParameters?: GetShiftsPagedShiftShiftsPagedGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ShiftPageResponse>>;
    public getShiftsPagedShiftShiftsPagedGet(requestParameters?: GetShiftsPagedShiftShiftsPagedGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ShiftPageResponse>>;
    public getShiftsPagedShiftShiftsPagedGet(requestParameters?: GetShiftsPagedShiftShiftsPagedGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const first = requestParameters?.first;
        const rows = requestParameters?.rows;
        const search = requestParameters?.search;
        const sortField = requestParameters?.sortField;
        const sortOrder = requestParameters?.sortOrder;
        const startDate = requestParameters?.startDate;
        const endDate = requestParameters?.endDate;
        const startTime = requestParameters?.startTime;
        const endTime = requestParameters?.endTime;
        const limit = requestParameters?.limit;

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'first',
            <any>first,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'rows',
            <any>rows,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'search',
            <any>search,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort_field',
            <any>sortField,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sort_order',
            <any>sortOrder,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'start_date',
            <any>startDate,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'end_date',
            <any>endDate,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'start_time',
            <any>startTime,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'end_time',
            <any>endTime,
            QueryParamStyle.Form,
            true,
        );

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'limit',
            <any>limit,
            QueryParamStyle.Form,
            true,
        );

        let localVarHeaders = this.defaultHeaders;

        // authentication (HTTPBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('HTTPBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/shift/shifts/paged`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ShiftPageResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get shifts by one or more IDs
     * Return only the shifts whose database IDs were explicitly requested.
     * @endpoint get /shift/shifts/by_ids
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getShiftsByIdsShiftShiftsByIdsGet(requestParameters: GetShiftsByIdsShiftShiftsByIdsGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<ShiftResponse>>;
    public getShiftsByIdsShiftShiftsByIdsGet(requestParameters: GetShiftsByIdsShiftShiftsByIdsGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ShiftResponse>>>;
    public getShiftsByIdsShiftShiftsByIdsGet(requestParameters: GetShiftsByIdsShiftShiftsByIdsGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ShiftResponse>>>;
    public getShiftsByIdsShiftShiftsByIdsGet(requestParameters: GetShiftsByIdsShiftShiftsByIdsGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const ids = requestParameters?.ids;
        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling getShiftsByIdsShiftShiftsByIdsGet.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'ids',
            <any>ids,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (HTTPBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('HTTPBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/shift/shifts/by_ids`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ShiftResponse>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
