/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppSchemasOperationsErrorResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { ShiftCreate } from '../model/models';
import { ShiftCreatedResponse } from '../model/models';
import { ShiftResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateShiftShiftCreateShiftPostRequestParams {
    shiftCreate: ShiftCreate;
}

export interface GetAllShiftsShiftShiftsGetRequestParams {
    startDate?: string | null;
    endDate?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    limit?: number | null;
}

export interface GetShiftsByIdsShiftShiftsByIdsGetRequestParams {
    ids: Array<number>;
}


export interface ShiftsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Shift
     * Create a shift, then attach its selfies and nested bus inspections.  The shift row is written first because child rows need the database-assigned &#x60;&#x60;shift_id&#x60;&#x60;. After that, selfies and inspections are persisted using the nested request payload supplied by the client.
     * @endpoint post /shift/create_shift/
* @param requestParameters
     */
    createShiftShiftCreateShiftPost(requestParameters: CreateShiftShiftCreateShiftPostRequestParams, extraHttpRequestParams?: any): Observable<ShiftCreatedResponse>;

    /**
     * Get all shifts with optional date range and limit
     * Return shift rows with optional date-range filtering and pagination size.  Despite the name &#x60;&#x60;limit&#x60;&#x60;, this endpoint still returns a plain list of shift records. The filters are applied directly at the database query level to avoid loading unnecessary rows into memory.
     * @endpoint get /shift/shifts
* @param requestParameters
     */
    getAllShiftsShiftShiftsGet(requestParameters: GetAllShiftsShiftShiftsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<ShiftResponse>>;

    /**
     * Get shifts by one or more IDs
     * Return only the shifts whose database IDs were explicitly requested.
     * @endpoint get /shift/shifts/by_ids
* @param requestParameters
     */
    getShiftsByIdsShiftShiftsByIdsGet(requestParameters: GetShiftsByIdsShiftShiftsByIdsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<ShiftResponse>>;

}
