/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddGeofence } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { SmartFleetIframeUrlResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddGeofenceSmartfleetCreateGeofencePostRequestParams {
    userApiHash: string;
    addGeofence: AddGeofence;
}


export interface SmartfleetServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add Geofence
     * Add a geofence to the system.
     * @endpoint post /smartfleet/create-geofence
* @param requestParameters
     */
    addGeofenceSmartfleetCreateGeofencePost(requestParameters: AddGeofenceSmartfleetCreateGeofencePostRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Get Iframe Login Url
     * Return a Smart Fleet iframe login URL built from a server-side OTT exchange.
     * @endpoint get /smartfleet/iframe-login-url
*/
    getIframeLoginUrlSmartfleetIframeLoginUrlGet(extraHttpRequestParams?: any): Observable<SmartFleetIframeUrlResponse>;

}
