/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppSchemasOperationsErrorResponse } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { VehicleEnvelope } from '../model/models';
import { VehicleListEnvelope } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetVehicleVehicleVehicleVinGetRequestParams {
    vin: string;
}

export interface GetVehiclesVehicleVehiclesGetRequestParams {
    isActive?: boolean | null;
    operatorId?: number | null;
    page?: number;
    pageSize?: number;
}


export interface VehicleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Vehicle
     * Return one vehicle identified by VIN, enforcing operator scoping rules.
     * @endpoint get /vehicle/vehicle/{vin}
* @param requestParameters
     */
    getVehicleVehicleVehicleVinGet(requestParameters: GetVehicleVehicleVehicleVinGetRequestParams, extraHttpRequestParams?: any): Observable<VehicleEnvelope>;

    /**
     * Get Vehicles
     * Return a filtered, paginated list of vehicles visible to the caller.
     * @endpoint get /vehicle/vehicles/
* @param requestParameters
     */
    getVehiclesVehicleVehiclesGet(requestParameters: GetVehiclesVehicleVehiclesGetRequestParams, extraHttpRequestParams?: any): Observable<VehicleListEnvelope>;

}
