/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cordinates } from './cordinates';
import { GeofenceType } from './geofenceType';


export interface AddGeofence { 
    name: string;
    active?: boolean;
    device_id?: number;
    group_id?: number;
    type?: GeofenceType;
    polygon?: Array<Cordinates> | null;
    radius?: number | null;
    center?: Cordinates | null;
    polygon_color: string;
    speed_limit?: number | null;
}



