/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsTrendSeriesResponse } from './analyticsTrendSeriesResponse';


export interface AnalyticsTrendResponse { 
    dates: Array<string>;
    series: Array<AnalyticsTrendSeriesResponse>;
}

