/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnalyticsLastEventResponse { 
    bus: string;
    location: string;
    time: string;
    event_type: string;
    measurement: string;
    operator: string;
}

