/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsDrilldownResponse } from './analyticsDrilldownResponse';
import { AnalyticsReportingTileResponse } from './analyticsReportingTileResponse';


export interface AnalyticsReportingSummaryResponse { 
    /**
     * UTC timestamp for this report summary.
     */
    generated_at: string;
    source_date_from?: string | null;
    source_date_to?: string | null;
    tiles: Array<AnalyticsReportingTileResponse>;
    drilldowns: { [key: string]: AnalyticsDrilldownResponse; };
}

