/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnalyticsMetricTileResponse { 
    title: string;
    icon: string;
    color: string;
    primary: string;
    secondary?: string | null;
}

