/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnalyticsVehiclePerformanceResponse { 
    fleet_no: string;
    registration: string;
    operator: string;
    distance: string;
    trip_duration: string;
    speed_duration: string;
    idle_duration: string;
    high_risk_trips: number;
    score: number;
}

