/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsTableColumnResponse } from './analyticsTableColumnResponse';


export interface AnalyticsDrilldownResponse { 
    title: string;
    columns: Array<AnalyticsTableColumnResponse>;
    data: Array<{ [key: string]: any; }>;
}

