/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsSummaryItemResponse } from './analyticsSummaryItemResponse';
import { AnalyticsTrendResponse } from './analyticsTrendResponse';
import { Value } from './value';


export interface AnalyticsReportingTileResponse { 
    id: string;
    title: string;
    metric: string;
    value: Value;
    status?: string;
    icon: string;
    summary_items?: Array<AnalyticsSummaryItemResponse>;
    trend?: AnalyticsTrendResponse | null;
}

