/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsSummaryItemResponse } from './analyticsSummaryItemResponse';
import { AnalyticsTrendResponse } from './analyticsTrendResponse';


export interface AnalyticsTopKpiResponse { 
    id: string;
    value: string;
    secondary_text?: string | null;
    status?: string;
    summary_items?: Array<AnalyticsSummaryItemResponse>;
    trend?: AnalyticsTrendResponse | null;
}

