/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Value } from './value';


export interface AnalyticsSummaryItemResponse { 
    label: string;
    value: Value;
    drill_key?: string | null;
}

