/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Success/error marker used in shift responses.
 */
export enum AppSchemasShiftMessageResponse {

    Success = 'success',

    Error = 'error'
}

