/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Minimal error body returned by many operations endpoints.
 */
export interface AppSchemasOperationsErrorResponse { 
    detail: string;
}

