/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Common success/fail flags reused in envelope responses.
 */
export enum AppSchemasOperationsMessageResponse {

    Pass = 'pass',

    Fail = 'fail'
}

