/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Allowed labels for behind-schedule reports.
 */
export enum BehindScheduleInterval {

    _05Mins = '0-5 mins',

    _510Mins = '5-10 mins',

    _1015Mins = '10-15 mins',

    _15Mins = '15+ mins'
}

