/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BehindScheduleInterval } from './behindScheduleInterval';


/**
 * Nested request model for one behind-schedule report.
 */
export interface BehindScheduleReportIn { 
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    behind_schedule_interval: BehindScheduleInterval;
}



