/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Grouped response model for one behind-schedule event.
 */
export interface BehindScheduleInspectionResponse { 
    inspection_id: number;
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    pass_?: boolean | null;
    notes?: string | null;
    behind_schedule_interval?: string | null;
}

