/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusInspectionsIn } from './busInspectionsIn';


/**
 * One bus entry inside a shift creation request.
 */
export interface BusIn { 
    bus_id?: string | null;
    bus_number?: string | null;
    duty_number: string;
    replacement_bus?: boolean;
    license_disk_scan_succeeded?: boolean | null;
    destination_displayed?: boolean | null;
    inspections: BusInspectionsIn;
}

