/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BehindScheduleReportIn } from './behindScheduleReportIn';
import { InteriorInspectionIn } from './interiorInspectionIn';
import { PassengerCountIn } from './passengerCountIn';
import { ExteriorInspectionIn } from './exteriorInspectionIn';
import { DriverInspectionIn } from './driverInspectionIn';


/**
 * All inspection sections that can belong to one bus within a shift.
 */
export interface BusInspectionsIn { 
    external_inspected?: boolean;
    internal_inspected?: boolean;
    driver_inspected?: boolean;
    passenger_counts_done?: boolean;
    behind_schedule_reports_done?: boolean;
    external?: ExteriorInspectionIn | null;
    internal?: InteriorInspectionIn | null;
    driver?: DriverInspectionIn | null;
    passenger_counts?: Array<PassengerCountIn>;
    behind_schedule_reports?: Array<BehindScheduleReportIn>;
}

