/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverInspectionResponse } from './driverInspectionResponse';
import { PassengerCountInspectionResponse } from './passengerCountInspectionResponse';
import { BehindScheduleInspectionResponse } from './behindScheduleInspectionResponse';
import { ExteriorInspectionResponse } from './exteriorInspectionResponse';
import { InteriorInspectionResponse } from './interiorInspectionResponse';


/**
 * Nested grouped inspection sections for one bus in a read response.
 */
export interface BusInspectionGroupItemsResponse { 
    external_inspected?: boolean;
    internal_inspected?: boolean;
    driver_inspected?: boolean;
    passenger_counts_done?: boolean;
    behind_schedule_reports_done?: boolean;
    external?: ExteriorInspectionResponse | null;
    internal?: InteriorInspectionResponse | null;
    driver?: DriverInspectionResponse | null;
    passenger_counts?: Array<PassengerCountInspectionResponse>;
    behind_schedule_reports?: Array<BehindScheduleInspectionResponse>;
}

