/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemPhotoResponse } from './inspectionItemPhotoResponse';


/**
 * Grouped response model for one driver inspection.
 */
export interface DriverInspectionResponse { 
    inspection_id: number;
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    pass_?: boolean | null;
    notes?: string | null;
    prdp_scan_succeeded?: boolean | null;
    prdp_expiry_date?: string | null;
    driver_identified?: boolean | null;
    driver_fail_reason?: string | null;
    driver_name?: string | null;
    photos?: Array<InspectionItemPhotoResponse>;
}

