/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemIn } from './inspectionItemIn';


/**
 * Nested request model for one external bus inspection.
 */
export interface ExteriorInspectionIn { 
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    tyres: InspectionItemIn;
    windows: InspectionItemIn;
    other: InspectionItemIn;
}

