/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemResponse } from './inspectionItemResponse';


/**
 * Grouped response model for one external inspection.
 */
export interface ExteriorInspectionResponse { 
    inspection_id: number;
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    pass_?: boolean | null;
    notes?: string | null;
    tyres: InspectionItemResponse;
    windows: InspectionItemResponse;
    other: InspectionItemResponse;
}

