/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body used to exchange a refresh token for a new ID token.
 */
export interface FirebaseRefreshRequest { 
    refresh_token: string;
}

