/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusInspectionGroupItemsResponse } from './busInspectionGroupItemsResponse';


/**
 * Top-level grouped read model returned by bus-inspection endpoints.
 */
export interface GroupedBusInspectionResponse { 
    shift_id: number;
    user_id: string;
    bus_id: string;
    fleet_number?: string | null;
    duty_number?: string | null;
    replacement_bus?: boolean;
    license_disk_scan_succeeded?: boolean | null;
    destination_displayed?: boolean | null;
    inspections: BusInspectionGroupItemsResponse;
}

