/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Inline image attached to one checklist item inside an inspection.
 */
export interface InspectionItemPhotoIn { 
    timestamp: string;
    lat: number;
    lon: number;
    photo: string;
}

