/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemPhotoIn } from './inspectionItemPhotoIn';


/**
 * Pass/fail result, optional reason, and optional photos for one item.
 */
export interface InspectionItemIn { 
    pass_?: boolean;
    reason?: string | null;
    photos?: Array<InspectionItemPhotoIn>;
}

