/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemPhotoResponse } from './inspectionItemPhotoResponse';


/**
 * Grouped checklist item response with pass/fail status and photos.
 */
export interface InspectionItemResponse { 
    pass_?: boolean | null;
    reason?: string | null;
    photos?: Array<InspectionItemPhotoResponse>;
}

