/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Photo response nested inside grouped checklist items.
 */
export interface InspectionItemPhotoResponse { 
    id: number;
    timestamp: string;
    lat: number;
    lon: number;
    photo: string;
    created_at: string;
}

