/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemResponse } from './inspectionItemResponse';


/**
 * Grouped response model for one internal inspection.
 */
export interface InteriorInspectionResponse { 
    inspection_id: number;
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    pass_?: boolean | null;
    notes?: string | null;
    fire_extinguisher_present?: boolean | null;
    seats: InspectionItemResponse;
    aisle: InspectionItemResponse;
    other: InspectionItemResponse;
}

