/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InspectionItemIn } from './inspectionItemIn';


/**
 * Nested request model for one internal bus inspection.
 */
export interface InteriorInspectionIn { 
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    fire_extinguisher_present?: boolean;
    seats: InspectionItemIn;
    aisle: InspectionItemIn;
    other: InspectionItemIn;
}

