/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Grouped response model for one passenger-count event.
 */
export interface PassengerCountInspectionResponse { 
    inspection_id: number;
    internal_inspection_id: string;
    inspection_time: string;
    inspection_lat: number;
    inspection_lon: number;
    pass_?: boolean | null;
    notes?: string | null;
    count?: number | null;
    number_seated?: number | null;
    number_standing?: number | null;
}

