/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Base64 photo payload supplied inline inside JSON requests.
 */
export interface PhotoIn { 
    timestamp: string;
    lat: number;
    lon: number;
    photo: string;
}

