/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Inline selfie payload captured as part of a shift.
 */
export interface SelfieIn { 
    timestamp: string;
    lat: number;
    lon: number;
    photo: string;
}

