/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppSchemasShiftMessageResponse } from './appSchemasShiftMessageResponse';


/**
 * Response returned after a shift row and its child records are created.
 */
export interface ShiftCreatedResponse { 
    status: number;
    message: AppSchemasShiftMessageResponse;
    shift_id: number;
}



