/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusIn } from './busIn';
import { SelfieIn } from './selfieIn';


/**
 * Top-level JSON payload for creating one complete shift.
 */
export interface ShiftCreate { 
    user_id: string;
    start_time: string;
    end_time: string;
    start_lat: number;
    start_lon: number;
    end_lat: number;
    end_lon: number;
    device_id: string;
    selfies: Array<SelfieIn>;
    busses: Array<BusIn>;
}

