/**
 * FS Bus API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShiftResponse } from './shiftResponse';


/**
 * Server-side page of shift rows for PrimeNG lazy tables.
 */
export interface ShiftPageResponse {
    items: Array<ShiftResponse>;
    total: number;
    first: number;
    rows: number;
}
