/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Read model for one stored shift row.
 */
export interface ShiftResponse { 
    id: number;
    user_id?: string | null;
    user_name?: string | null;
    user_surname?: string | null;
    start_time: string;
    end_time: string;
    start_lat: number;
    start_lon: number;
    end_lat: number;
    end_lon: number;
    device_id: string;
    created_at: string;
    inspection_count?: number;
    failed_inspection_count?: number;
}
