/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmartFleetIframeUrlResponse { 
    /**
     * Smart Fleet OTT login URL for iframe use.
     */
    iframe_url: string;
}

