/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Refresh response model.  It currently reuses the same shape as ``UserLoginResponse`` so clients can handle login and refresh results consistently.
 */
export interface UserRefreshResponse { 
    access_token: string;
    refresh_token: string;
    token_type: string;
    role: string;
    user_id: string;
    name?: string | null;
    surname?: string | null;
    expires_at?: string | null;
}

