/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enriched login response returned after successful authentication.  This combines Firebase-issued tokens with local application user metadata so clients can bootstrap a session from a single response payload.
 */
export interface UserLoginResponse { 
    access_token: string;
    refresh_token: string;
    token_type: string;
    role: string;
    user_id: string;
    name?: string | null;
    surname?: string | null;
    expires_at?: string | null;
}

