/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response returned after successfully creating a user.
 */
export interface UserCreateResponse { 
    user_id: number;
    firebase_uid: string;
    full_name: string;
    name?: string | null;
    surname?: string | null;
    email: string;
    role: string;
    operator_id?: number | null;
    is_active: boolean;
    created_at: string;
}

