/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Credentials submitted by a client that wants to log in.
 */
export interface UserLoginRequest { 
    email: string;
    password: string;
}

