/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload for creating a new application user record.
 */
export interface UserCreateRequest { 
    full_name: string;
    email: string;
    password: string;
    role: string;
    operator_id?: number | null;
    is_active?: boolean;
}

