/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One analytics event row for a vehicle detail page.
 */
export interface VehicleEventDetailResponse { 
    event_time?: string | null;
    event_type: string;
    location?: string | null;
    measurement: string;
    driver?: string | null;
}

