/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One analytics trip row for a vehicle detail page.
 */
export interface VehicleTripDetailResponse { 
    trip_start?: string | null;
    trip_end?: string | null;
    driver?: string | null;
    start_location?: string | null;
    end_location?: string | null;
    distance_km: number;
    duration_minutes: number;
    speed_duration_minutes: number;
    route_score?: number | null;
    style_score?: number | null;
    risk_factor?: number | null;
    high_risk: boolean;
}

