/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One inspection row for a vehicle detail page.
 */
export interface VehicleInspectionHistoryResponse { 
    inspection_time: string;
    inspection_type: string;
    passed?: boolean | null;
    inspector?: string | null;
    notes?: string | null;
    failed_checks?: Array<string>;
    gps?: string | null;
}

