/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current Smart Fleet and latest-inspection status for one vehicle.
 */
export interface VehicleCurrentStatusResponse { 
    smart_fleet_device_id?: number | null;
    current_location?: string | null;
    last_ping_time?: string | null;
    latest_inspection_at?: string | null;
    latest_inspection_type?: string | null;
    latest_inspection_passed?: boolean | null;
}

