/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * API response model for master-data vehicles.
 */
export interface VehicleResponse { 
    vehicle_id: number;
    vin: string;
    registration_number: string | null;
    fleet_number: string | null;
    operator_id: number | null;
    operator_name: string | null;
    make: string | null;
    year: string | null;
    engine_number: string | null;
    gvm: number | null;
    tare: number | null;
    chassis_no: string | null;
    date_of_1st_reg: string | null;
    is_active: boolean;
    created_at: string;
}

