/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleDetailResponse } from './vehicleDetailResponse';
import { AppSchemasOperationsMessageResponse } from './appSchemasOperationsMessageResponse';


/**
 * Single-vehicle detail response wrapper.
 */
export interface VehicleDetailEnvelope { 
    message: AppSchemasOperationsMessageResponse;
    detail: VehicleDetailResponse;
}



