/**
 * FS Bus API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleResponse } from './vehicleResponse';
import { AppSchemasOperationsMessageResponse } from './appSchemasOperationsMessageResponse';


/**
 * Paginated vehicle list response wrapper.
 */
export interface VehicleListEnvelope { 
    message: AppSchemasOperationsMessageResponse;
    total: number;
    page: number;
    page_size: number;
    vehicles: Array<VehicleResponse>;
}



